// mutations
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS'

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const RECEIVE_CATEGORIES_OUTSTANDING = 'RECEIVE_CATEGORIES_OUTSTANDING'
