// mutations
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS'

export const ADD_TO_WEB_CART = 'ADD_TO_WEB_CART'
export const REMOVE_FROM_WEB_CART = 'REMOVE_FROM_WEB_CART'
export const UPDATE_QUANTITY_FROM_WEB_CART = 'UPDATE_QUANTITY_FROM_WEB_CART'
export const RECEIVE_WEB_CART_ITEMS = 'RECEIVE_WEB_CART_ITEMS'
export const CHECKOUT_WEB_CART = 'CHECKOUT_WEB_CART'
